# Wochenplan 02

...Vorbereitung von der 02. auf die 03.Einheit.

## Lernziele

In der zweiten Seminarwoche geht es darum, die Grundlagen von R und RStudio zu repetieren und zu erweitern.^[Falls Sie noch Probleme bei der Installation von R bzw. RStudio oder sonstige technische Schwierigkeiten haben, können Sie sich gerne weiterhin per E-Mail melden!] Für den weiteren Verlauf wollen wir *R als Sprache* auffassen – sowohl als Programmiersprache als auch als Sprache in einem metaphorischen Sinn. Wir wollen also ein komplexes System zur Kommunikation kennenlernen. Wie bei einer anderen Sprache gibt es auch hier Zeichen mit Bedeutungen (ähnliche wie Nomen, Verben, . . . ) und Regeln zur Verknüpfung dieser Zeichen (ähnlich wie eine Grammatik). Diese Grundlagen gilt es alle erstmal kennenzulernen und zu verstehen. Am Anfang wird vieles schwer fallen, mit der Zeit gewinnt man aber Sicherheit.

Der zentrale Punkt in dieser Vorstellung von R als Sprache ist dabei folgender: Wir lernen eine Sprache dadurch, dass wir sie immer wieder anwenden, Probleme lösen und vor allem auch Fehler machen. R als Software und als Programmiersprache hat eine steile Lernkurve und zu Beginn werden viele Probleme auftauchen. Im Umgang mit den Problemen soll allerdings auch eine eigene Arbeitsweise mit dem Programm erlernt werden (Fehlermeldungen lesen, Lösungsstrategien im Codieren erlernen, selber Hilfe suchen, . . . ). Für die beständige Erweiterung der Grundlagen und das Erlernen der “Sprache R” besteht eine Herausforderung darin, den Weg zwischen scheinbarer *Trivialität* und überfordernder *Komplexität* zu finden: Es gilt die kleinen Schritte ernstzunehmen, sonst werden die grossen Schritte sehr schnell mühsam.

Für die zweite Seminarwoche lassen sich folgende Seminarziele festhalten:

* Sie können die verschiedenen Funktionsweisen der vier Fenster in RStudio erläutern.
* Sie verstehen den Unterschied zwischen der Arbeit in der Konsole und im Skript.
* Sie verstehen, wie und wozu man im Skript kommentiert.
* Sie haben R-Markdown als erweitertes Skript und Arbeitsinstrument kennengelernt.
* Sie wissen, was ein Arbeitsverzeichnis in R ist und wozu es gut ist.
* Sie verstehen das erste Grundelement der “Sprache R”: *Funktionen*
  + Sie wissen, wie Funktionen aufgebaut sind
  + Sie wissen, wie Sie sich Hilfe zu Funktionen holen;
  + Sie wissen, was Argumente in einer Funktion bewirken.
* Sie verstehen das zweite Grundelement der “Sprache R”: *Objekte*
  + Sie verstehen, was es bedeutet, dass in R “alles ein Objekt ist”;
  + Sie wissen, wie man sich die jeweils aktuell verfügbare Objekte anzeigen lässt;
  + Sie haben das Zusammenspiel von Funktionen und Objekte kennengelernt;
  + Sie kennen bereits drei verschiedenen Arten von Objekten.

## Aufgaben

1. Fassen Sie noch einmal für sich und in eigenen Worten die Funktionen der vier Fenster von RStudio zusammen.

2. Was ist der Vorteil der Arbeit im Skript gegenüber dem Schreiben von Code direkt in der Konsole? Und was könnten dann die Vorteile davon sein, mit R Markdown zu arbeiten? Und wann könnten Sie trotzdem besser mit einem klassischen Skript arbeiten? Schauen Sie sich auch die Formatierungsmöglichkeiten für Fliesstext in den Cheatsheets zu R Markdown an (siehe [hier](https://rmarkdown.rstudio.com/articles.html))!

3. Öffnen Sie eine neue R Markdown Datei. Versuchen Sie Ihre bisherigen Notizen zu den Aufgaben und Ihren Code in dieser Datei unterzubringen (falls Sie dies nicht schon gemacht haben). Arbeiten Sie für die folgenden Aufgaben mit dieser Datei
weiter.

4. Versuchen Sie allgemein zu beschreiben, was Funktionen und was Objekte sind. Fügen Sie eine kurze Erläuterung in Ihr Markdown-Dokument zur Frage ein, was im folgenden Code jeweils Funktionen und was Objekte (und wenn letzteres, welche Art von Objekt) sind:
```{r eval = F}
sqrt(x)
help("sqrt")
?help
y <- c(1, 3, 4, 5, 6, 7, NA)
z <- c(7, 8, 10, 11)
is.logical(TRUE)
```

5. Sehen Sie sich die Hilfeseite der Funktion `matrix()` an. Wozu dient diese Funktion? Welche Argumente akzeptiert / benötigt sie und wozu dienen diese? Illustrieren Sie die Funktionsweise anhand von einem Beispiel.


Versuchen Sie abschliessend Ihr Markdown Dokument zu ‘knitten’ und so daraus ein PDF Dokument zu erstellen. ACHTUNG: Damit dies funktioniert, muss Ihr Kode fehlerfrei sein. Falls dies nicht klappt sollte notieren Sie bitte wieso und erstellen auf einem anderen Weg ein PDF Ihrer Lösungen. Beschriften Sie Ihr Dokument mit FL02_NameVorname.pdf und geben das Dokument via OLAT vor der nächsten Einheit ab.
