# Wochenplan 05

...Vorbereitung von der 06. auf die 07.Einheit.

## Lernziele

Über die vergangenen Wochen haben wir zahlreiche grundlegende Aspekte der Arbeit mit R kennengelernt. Als Vorbereitung im Rahmen des Wochenplans 06 sollen Sie diese Inhalte noch einmal Revue passieren lassen. Im Rahmen dieser Repetition werden weiter zwei neue Dinge vermittelt werden: Auf der einen Seite erfolgt die Schulung aktiver Rezeptionsfertigkeiten (sprich: R-Code lesen und verstehen lernen). Auch dies ist eine wichtige Arbeitstechnik in R. Auf der anderen Seite sollen Sie mit dem rezipierten Code das Prinzip der Inferenzstatistik (und der Stichprobenverteilung sowie des Standardfehlers) in R veranschaulicht bekommen.

Konkret lassen sich folgende Seminarziele festhalten:

- Sie können von einer anderen Person geschriebenen R-Code entziffern und mit Kommentaren versehen. 

- Sie entwickeln dabei ein Gefühl für unterschiedliche Arten, Code lesbar zu gestalten.

- Sie wissen, wie selbstgeschriebene Funktionen in R aussehen und können diese Schritt für Schritt interpretieren. 

- Sie entwickeln Ihr Verständnis davon weiter, wie in R Grafiken genutzt und angepasst werden, um statistische Inhalte zu visualisieren. 

- Sie nutzen R um über Konzepte der Inferenzstatistik (wie den Standardfehler) nachzudenken.


## Aufgaben

1. Öffnen Sie die Datei "standardfehler.R" in RStudio (auf OLAT verfügbar). Gehen Sie den Code Zeile für Zeile durch, zuerst ohne diesen auszführen. Versuchen Sie dabei *im Detail* zu verstehen, was hier vor sich geht. Halten Sie Ihre Einsichten als Kommentare fest. Auch allfällige Fragen und Unklarheiten können Sie einfach als Kommentare notieren.

2. Fügen Sie anschliessend die von Ihnen gesammelten Fragen und die dazugehörigen Codezeilen in ein Markdown-Dokument ein. Die Codezeilen sollen als R Chunk im Markdown aufgeführt sein, aber mit der Ergänzung `eval = FALSE` versehen. Im Fliesstext des Markdowns können Sie Ihre Kommentare und Fragen erläutern. Führen Sie den Code Schritt für Schritt aus (und löschen Sie die Kommentare von Unklarhheiten, die Ihnen nach der Ausführung des Codes einleuchten).

3. Konzentrieren Sie anschliessend nochmals auf den letzten Punkt ("`# *Gemeinsame Darstellung*...`"). Was hat dieser Codeabschnitt mit dem Konzept des Standardfehlers / des Stichprobenfehlers zu tun? Spielen Sie ein wenig mit den verschiedenen Parametern. Welche Zusammenhänge, die für den Standardfehler wesentlich sind, lassen sich erkennen?

4. Sammeln Sie Punkte, die Ihnen aus den bisherigen Seminareinheiten unklar geblieben sind. Welche Aspekte würden Sie gerne noch einmal wiederholen/erläutert bekommen? Sammeln Sie diese Aspekte ebenfalls im Markdown auf dieselbe Art und Weise wie bei Aufgabe 2.

&nbsp;

Generieren Sie ein PDF aus dem Markdown, in welchem Sie allfällige Fragen sowie Unklarheiten und die dazugehörigen Codechunks aus Aufgabe 2 und 4 gesammelt haben. Beschriften Sie Ihr Dokument mit FL06_NameVorname.pdf und geben das Dokument via OLAT.
