# Wochenplan 07

...Vorbereitung von der 07. auf die 08.Einheit.

## Lernziele

In der zweiten Hälfte des Semester möchten wir das statistische Arbeiten mit R anhand des Umgangs mit "echten" Daten kennenlernen. Dazu nutzen wir Daten aus dem *European Social Survey* (ESS). Am Beginn der Arbeit mit einem Datensatz steht das **Kennenlernen der Daten**: Es gilt die Variablen und ihre Ausprägungen zu verstehen, erste Plausibilitätsprüfungen durchzuführen und Daten für die spätere Analyse aufzubereiten. Diese Techniken sollen Sie im Rahmen des siebten Wochenplans kennenlernen und so die Grundlage schaffen, in den folgenden Einheiten statistische Analysen mit dem Datensatz vorzunehmen.

Konkret lassen sich folgende Lernziele festhalten:

* Sie können einen CSV-Datensatz in R laden und kennen die Vor- und Nachteile dieses Dateiformats.
* Sie können einen geladen Datensatz anhand verschiedener Funktionen und in unterschiedlichem Detailliertheitsgrad beschreiben.  
* Sie kennen erste Techniken zur Plausibilitätsprüfung von Datensätzen.  
* Sie kennen erste Techniken zur Datenaufbereitung.   
* Sie verstehen, wie und wozu man zufällige Teildatensätze erstellt.   


## Aufgaben

1. Laden Sie sich den Datensatz "ESS1-8e01.csv" und ESS-Fragebogen (das Codebook) herunter (via OLAT) und speichern Sie die Dateien in Ihrem Arbeitsverzeichnis. Laden Sie anschliessend den Datensatz in RStudio über die Funktion 'read.csv()'. Betrachten Sie den Datensatz über die Funktion 'View()' oder indem Sie auf Ihr erstelltes Objekt im Fenster "Environment" klicken. Vergleichen Sie für einzelne Variablen die Informationen im Datensatz mit den entsprechenden Fragebogenfragen!

2. Öffnen Sie nun die Datei "ESS1-8e01.csv" in einem Tabellenkalkulations- oder einem Textbearbeitungsprogramm (z.B. Microsoft Excel, dem Windows-Editor oder TextEdit auf Mac).
- Vergleichen Sie die beiden Varianten (Ihr Dataframe in RStudio und die im Textbearbeitungsprogramm geöffnete Datei), um das Dateiformat "CSV" besser zu verstehen.
- Ersetzen Sie anschliessend im Tabellenkalkulations- oder Textbearbeitungsprogramm die Kommas in der "ESS1-8e01.csv" Datei mit Strichpunkten und speichern Sie diese neue Version ab. Gehen Sie zurück zu R Studio und versuchen Sie, die neue Version des Datensatzes zu laden. Welchen Paramter müssen Sie anpassen, damit das funktioniert?
- Was denken Sie könnten Vorteile des CSV-Formats sein? Welche möglichen Nachteile im Vergleich zu anderen Dateiformaten (Excel, SPSS ...) sind denkbar?

3. Versuchen Sie mit Funktionen, die Sie bisher kennengelernt haben, den geladenen Datensatz kurz zu beschreiben. 

4. In den Variablen zum Alter und den Bildungsabschlüssen der befragten Personen haben sich einige Fehler eingeschlichen. Was sind die Fehler? Und welche Fälle betrifft das (Fallnummer)?

5. *Bonusaufgabe*: In den folgenden Wochen möchten wir nicht mit dem ganzen Datensatz arbeiten, sondern lediglich mit einer zufälligen Auswahl von 200 Fällen. Versuchen Sie, einen solchen Teildatensatz randomisiert zu erstellen und speichern Sie ihn mittels der Funktion 'write.csv()' unter dem Namen "TD_ESS1-8e01.csv" ab.


Arbeiten Sie für die Falllösung wie immer mit RMarkdown und generieren Sie sich ein PDF Ihrer Lösungen. Beschriften Sie Ihr Dokument mit "FL07_NameVorname.pdf" und geben das Dokument via OLAT vor der nächsten Einheit ab.

