# Wochenplan 09

...zur 09. & 10. Einheit, Umgang mit Faktoren

## Lernziele

Aufbauend auf unserer bisherigen Arbeit mit Kreuztabellen besteht das Lernziel für diese Woche darin, dass Sie sich mit einem für die tägliche Arbeit mit R wichtigen Datenformat vertraut machen: Faktoren. Faktoren sind eine geeignete Art, kategoriale -- d.h. nominale und ordinale -- Daten in R zu repräsentieren. Der Umgang mit dieser Art von Daten ist allerdings nicht ganz leicht und erfordert ein wenig Übung. 

Die folgenden konkreten Lernziele lassen sich für ein erstes Kennenlernen von Faktoren formulieren:

* Sie können dafür geeignete Variablen in Faktoren umwandeln.
* Sie verstehen den Unterschied zwischen geordneten und ungeordneten Faktoren und können beide in R erstellen. 
* Sie verstehen die spezifische Zwei-Ebenen-Struktur von Faktoren und insbesondere die Rolle von "Levels".
* Sie wissen, wie man die Levels eines Faktors definiert.
* Sie wissen, wie man Levels neu benennt, umsortiert, zusammenfasst und/oder nicht benötigte Levels entfernt. 


## Aufgaben

1. Laden Sie Ihr Datenimport-Skript und fügen Sie einen Abschnitt zur Definition und Aufbereitung einzelner Variablen als Faktoren ein. Arbeiten Sie anschliessend in einem R Markdown weiter.

2. Gehen Sie unseren Übungsdatensatz konzentriert durch und überlegen Sie, welche Variablen als geordnete oder ungeordnete Faktoren gespeichert werden sollten. 

3. Definieren Sie nun jede dieser Variablen als Faktor (die einzige Ausnahme soll die Variable "isco08" sein).

4. Überprüfen Sie mittels Kreuztabellen, ob Ihre Faktoren sinnvoll und fehlerfrei definiert sind. 

5. Inkludieren Sie die einwandfrei funktionierenden Lösungen zur Faktorendefinition in Ihr Datenimportskript. Testen Sie danach, ob das Skript funktioniert: Löschen Sie Ihre Environment (und alle Objekte), laden Sie mittels `source()` den Datensatz neu und rufen Sie dann -- als Test -- eine als Faktor definierte Variable auf.

&nbsp;

Arbeiten Sie für die Falllösung wie immer mit R Markdown und generieren Sie sich ein PDF Ihrer Lösungen. Beschriften Sie Ihr Dokument mit "FL09_NameVorname.pdf" und geben das Dokument via OLAT vor der nächsten Einheit ab.