--- 
title: "Sozialwissenschaftliche Datenanalyse mit R"
author: "Kenneth Horvath & Guy Schwegler"
date: "HS 2021"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: TRUE
github-repo: rstudio/bookdown-demo
description: "Dieses Dokument ist ein Bookdown für das Hauptseminar 'Sozialwissenschaftliche Datenanalyse mit R' im HS21 und dient als Ergebnisicherung im Seminarverlauf."
---

# Einführung {-}

Das Seminar "Sozialwissenschaftliche Datenanalyse mit R" bietet eine systematische Einführung in das Statistikpaket R sowie die Benutzeroberfläche RStudio. R ist eine Open Source Software, die sich unter anderem durch Flexibilität sowie durch vielfältige Möglichkeiten der numerischen und grafischen Datenanalyse auszeichnet. Das Seminar führt auf der einen Seite allgemein in den Aufbau des Programms und dessen Funktionsweisen ein. Auf der anderen Seite werden gewisse statistische Verfahren auch in inhaltliche Abstimmung mit der Vorlesung "Grundlagen der multivariaten Statistik" vermittelt. Anhand der Funktionsweisen und der Verfahren werden dann Techniken des effizienten Datenmanagements, Möglichkeiten zur eigenständigen Programmierung von kleinen Funktionen sowie Formen der grafischen Datenanalyse und Ergebnisdarstellung besprochen.

Das vorliegende Dokument ist ein sogenanntes Bookdown [@R-bookdown], siehe auch [hier](https://bookdown.org/), und dient der Ergebnissicherung im Seminarverlauf. Das heisst dass die im Seminar besprochene Themen hiernochmals schriftlich festgehalten, diskutiert und allenfalls mit Literatur ergänzt werden (siehe für allgemeine Literatur etwa @DiazBone2019, @Kabacoff2015 oder @Manderscheid2017). Das Bookdown wird laufend aktualisiert. Ebenfalls werden in diesem Bookdown die Lösungen für die im Seminar beziehungsweise in den Wochenplänen gestellten Aufgaben präsentiert (Falllösungen).





