<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Wochenplan 07 | Sozialwissenschaftliche Datenanalyse mit R</title>
  <meta name="description" content="Dieses Dokument ist ein Bookdown für das Hauptseminar ‘Sozialwissenschaftliche Datenanalyse mit R’ im HS21 und dient als Ergebnisicherung im Seminarverlauf." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Wochenplan 07 | Sozialwissenschaftliche Datenanalyse mit R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Dieses Dokument ist ein Bookdown für das Hauptseminar ‘Sozialwissenschaftliche Datenanalyse mit R’ im HS21 und dient als Ergebnisicherung im Seminarverlauf." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Wochenplan 07 | Sozialwissenschaftliche Datenanalyse mit R" />
  
  <meta name="twitter:description" content="Dieses Dokument ist ein Bookdown für das Hauptseminar ‘Sozialwissenschaftliche Datenanalyse mit R’ im HS21 und dient als Ergebnisicherung im Seminarverlauf." />
  

<meta name="author" content="Kenneth Horvath &amp; Guy Schwegler" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="wochenplan-06.html"/>
<link rel="next" href="wochenplan-08.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R - HS21</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Einführung</a></li>
<li class="chapter" data-level="1" data-path="wocheplan-01.html"><a href="wocheplan-01.html"><i class="fa fa-check"></i><b>1</b> Wocheplan 01</a>
<ul>
<li class="chapter" data-level="1.1" data-path="wocheplan-01.html"><a href="wocheplan-01.html#sozialwissenschaftliche-datenanalyse"><i class="fa fa-check"></i><b>1.1</b> Sozialwissenschaftliche Datenanalyse</a></li>
<li class="chapter" data-level="1.2" data-path="wocheplan-01.html"><a href="wocheplan-01.html#ziel-des-kurses"><i class="fa fa-check"></i><b>1.2</b> Ziel des Kurses</a></li>
<li class="chapter" data-level="1.3" data-path="wocheplan-01.html"><a href="wocheplan-01.html#r-als-programm-rstudio"><i class="fa fa-check"></i><b>1.3</b> R als Programm &amp; RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="wocheplan-01.html"><a href="wocheplan-01.html#lernziele-der-ersten-woche"><i class="fa fa-check"></i><b>1.4</b> Lernziele der ersten Woche</a></li>
<li class="chapter" data-level="1.5" data-path="wocheplan-01.html"><a href="wocheplan-01.html#aufgaben-der-ersten-woche"><i class="fa fa-check"></i><b>1.5</b> Aufgaben der ersten Woche</a></li>
<li class="chapter" data-level="1.6" data-path="wocheplan-01.html"><a href="wocheplan-01.html#ergänzung-standardabweichung-zwischen-grundgesamtheit-und-stichprobe"><i class="fa fa-check"></i><b>1.6</b> Ergänzung: Standardabweichung zwischen Grundgesamtheit und Stichprobe</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="wochenplan-02.html"><a href="wochenplan-02.html"><i class="fa fa-check"></i><b>2</b> Wochenplan 02</a>
<ul>
<li class="chapter" data-level="2.1" data-path="wochenplan-02.html"><a href="wochenplan-02.html#lernziele"><i class="fa fa-check"></i><b>2.1</b> Lernziele</a></li>
<li class="chapter" data-level="2.2" data-path="wochenplan-02.html"><a href="wochenplan-02.html#aufgaben"><i class="fa fa-check"></i><b>2.2</b> Aufgaben</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="wochenplan-03.html"><a href="wochenplan-03.html"><i class="fa fa-check"></i><b>3</b> Wochenplan 03</a>
<ul>
<li class="chapter" data-level="3.1" data-path="wochenplan-03.html"><a href="wochenplan-03.html#lernziele-1"><i class="fa fa-check"></i><b>3.1</b> Lernziele</a></li>
<li class="chapter" data-level="3.2" data-path="wochenplan-03.html"><a href="wochenplan-03.html#aufgaben-1"><i class="fa fa-check"></i><b>3.2</b> Aufgaben</a></li>
<li class="chapter" data-level="3.3" data-path="wochenplan-03.html"><a href="wochenplan-03.html#ergänzung-seitenumbruch-im-rmarkdown"><i class="fa fa-check"></i><b>3.3</b> Ergänzung: Seitenumbruch im RMarkdown</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="wochenplan-04.html"><a href="wochenplan-04.html"><i class="fa fa-check"></i><b>4</b> Wochenplan 04</a>
<ul>
<li class="chapter" data-level="4.1" data-path="wochenplan-04.html"><a href="wochenplan-04.html#lernziele-2"><i class="fa fa-check"></i><b>4.1</b> Lernziele</a></li>
<li class="chapter" data-level="4.2" data-path="wochenplan-04.html"><a href="wochenplan-04.html#aufgaben-2"><i class="fa fa-check"></i><b>4.2</b> Aufgaben</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="wochenplan-05.html"><a href="wochenplan-05.html"><i class="fa fa-check"></i><b>5</b> Wochenplan 05</a>
<ul>
<li class="chapter" data-level="5.1" data-path="wochenplan-05.html"><a href="wochenplan-05.html#lernziele-wp05"><i class="fa fa-check"></i><b>5.1</b> Lernziele WP05</a></li>
<li class="chapter" data-level="5.2" data-path="wochenplan-05.html"><a href="wochenplan-05.html#hinweise-indizieren-subsetting"><i class="fa fa-check"></i><b>5.2</b> Hinweise Indizieren &amp; Subsetting</a></li>
<li class="chapter" data-level="5.3" data-path="wochenplan-05.html"><a href="wochenplan-05.html#aufgaben-wp05"><i class="fa fa-check"></i><b>5.3</b> Aufgaben WP05</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="wochenplan-06.html"><a href="wochenplan-06.html"><i class="fa fa-check"></i><b>6</b> Wochenplan 06</a>
<ul>
<li class="chapter" data-level="6.1" data-path="wochenplan-06.html"><a href="wochenplan-06.html#lernziele-3"><i class="fa fa-check"></i><b>6.1</b> Lernziele</a></li>
<li class="chapter" data-level="6.2" data-path="wochenplan-06.html"><a href="wochenplan-06.html#besprechung-skript-standardfehler.r"><i class="fa fa-check"></i><b>6.2</b> Besprechung Skript “standardfehler.R”</a></li>
<li class="chapter" data-level="6.3" data-path="wochenplan-06.html"><a href="wochenplan-06.html#ggplot2-darstellung"><i class="fa fa-check"></i><b>6.3</b> ggplot2 Darstellung</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="wochenplan-07.html"><a href="wochenplan-07.html"><i class="fa fa-check"></i><b>7</b> Wochenplan 07</a>
<ul>
<li class="chapter" data-level="7.1" data-path="wochenplan-07.html"><a href="wochenplan-07.html#lernziele-4"><i class="fa fa-check"></i><b>7.1</b> Lernziele</a></li>
<li class="chapter" data-level="7.2" data-path="wochenplan-07.html"><a href="wochenplan-07.html#aufgaben-3"><i class="fa fa-check"></i><b>7.2</b> Aufgaben</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="wochenplan-08.html"><a href="wochenplan-08.html"><i class="fa fa-check"></i><b>8</b> Wochenplan 08</a>
<ul>
<li class="chapter" data-level="8.1" data-path="wochenplan-08.html"><a href="wochenplan-08.html#lernziele-5"><i class="fa fa-check"></i><b>8.1</b> Lernziele</a></li>
<li class="chapter" data-level="8.2" data-path="wochenplan-08.html"><a href="wochenplan-08.html#aufgaben-4"><i class="fa fa-check"></i><b>8.2</b> Aufgaben</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="./">Universität Luzern</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Sozialwissenschaftliche Datenanalyse mit R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="wochenplan-07" class="section level1" number="7">
<h1><span class="header-section-number">7</span> Wochenplan 07</h1>
<p>…zur Einheit der 07. und 08. Woche.</p>
<div id="lernziele-4" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Lernziele</h2>
<p>In der zweiten Hälfte des Semester möchten wir das statistische Arbeiten mit R anhand des Umgangs mit “echten” Daten kennenlernen. Dazu nutzen wir Daten aus dem <em>European Social Survey</em> (ESS). Am Beginn der Arbeit mit einem Datensatz steht das <strong>Kennenlernen der Daten</strong>: Es gilt die Variablen und ihre Ausprägungen zu verstehen, erste Plausibilitätsprüfungen durchzuführen und Daten für die spätere Analyse aufzubereiten. Diese Techniken sollen Sie im Rahmen des siebten Wochenplans kennenlernen und so die Grundlage schaffen, in den folgenden Einheiten statistische Analysen mit dem Datensatz vorzunehmen.</p>
<p>Konkret lassen sich folgende Lernziele festhalten:</p>
<ul>
<li>Sie können einen CSV-Datensatz in R laden und kennen die Vor- und Nachteile dieses Dateiformats.</li>
<li>Sie können einen geladen Datensatz anhand verschiedener Funktionen und in unterschiedlichem Detailliertheitsgrad beschreiben.<br />
</li>
<li>Sie kennen erste Techniken zur Plausibilitätsprüfung von Datensätzen.<br />
</li>
<li>Sie kennen erste Techniken zur Datenaufbereitung.<br />
</li>
<li>Sie verstehen, wie und wozu man zufällige Teildatensätze erstellt.</li>
</ul>
</div>
<div id="aufgaben-3" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> Aufgaben</h2>
<ol style="list-style-type: decimal">
<li>Laden Sie sich den Datensatz “ESS1-8e01.csv” und ESS-Fragebogen (das Codebook) herunter (via OLAT) und speichern Sie die Dateien in Ihrem Arbeitsverzeichnis. Laden Sie anschliessend den Datensatz in RStudio über die Funktion ‘read.csv().’ Betrachten Sie den Datensatz über die Funktion ‘View()’ oder indem Sie auf Ihr erstelltes Objekt im Fenster “Environment” klicken. Vergleichen Sie für einzelne Variablen die Informationen im Datensatz mit den entsprechenden Fragebogenfragen!</li>
</ol>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="wochenplan-07.html#cb279-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Users/SchweglG/R_Daten/06_HS21/R_Seminar-HS21&quot;</span>)</span></code></pre></div>
<p>Als erster Schritt gilt es Ihr Arbeitsverzeichnis zu definieren, das heisst der Ort, an dem auch Ihre Daten abgelegt sind (ggfs. sind diese noch in einem weiteren Unterordner). In diesem Arbeitsverzeichnis würden auch allfällige weitere Daten liegen oder später automatisch von R abgespeichert (vgl. Aufgabe 5).</p>
<p>Sobald Sie die Kodezeilen bis <code>daten_ess &lt;- read.csv(file =""</code> eingegeben haben sollten Sie auf die Tabulatortaste klicken können und so Ihr Datenfile auswählen (und eben auch auf weitere Unterordner Ihres Arbeitsverzeichnis zurückgreifen). Hier gilt es allerdings folgendes zu beachten (vgl. auch <a href="https://bookdown.org/yihui/rmarkdown-cookbook/working-directory.html">diese Erläuterungen</a>): Standardmässig ist das Arbeitsverzeichnis für R-Codechunks das Verzeichnis, in welchem Ihr RMarkdown-Dokument abgelegt ist. In RStudio können Sie diesen Standard auch über das Menü “Tools” -&gt; “Global Options” -&gt; “R Markdown” ändern. Hier gibt es nun zwei weitere Möglichkeiten: Sie können das aktuelle Arbeitsverzeichnis Ihrer R-Konsole (die Option “Current”) oder das Stammverzeichnis eines Projektes als Arbeitsverzeichnis verwenden (die Option “Project”).<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a> Mit “Current” sollte dann dasjene Verzeichnis ausgewählt werden, das wir auch über die Menüsteuerung zur Definition des Arbeitsverzeichnis auswählen. Jedoch wird damit noch nicht behoben, dass mit der Tabulatortaste weiter auf denjenigen Ordner zugegriffen wird, in dem das jeweils aktive RMardown-Dokument abgelegt ist. Deswegen ist es angebracht, vor dem Laden der Dateien auch nochmals das Arbeitsverzeichnis einzufügen:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="wochenplan-07.html#cb280-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;C:/Users/SchweglG/R_Daten/06_HS21/R_Seminar-HS21&quot;</span>)</span>
<span id="cb280-2"><a href="wochenplan-07.html#cb280-2" aria-hidden="true" tabindex="-1"></a>daten_ess <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">&quot;Daten/ESS1-8e01.csv&quot;</span>)</span></code></pre></div>
<p>Eine weitere Alternative wäre das Arbeitsverzeichnis über einen “Setup” Kode anzupassen:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="wochenplan-07.html#cb281-1" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;&#39;&#39;{r, setup, include=FALSE}</span></span>
<span id="cb281-2"><a href="wochenplan-07.html#cb281-2" aria-hidden="true" tabindex="-1"></a><span class="st"> knitr::opts_knit$set(root.dir = &quot;C:/Users/SchweglG/R_Daten/06_HS21/R_Seminar-HS21&quot;)</span></span>
<span id="cb281-3"><a href="wochenplan-07.html#cb281-3" aria-hidden="true" tabindex="-1"></a><span class="st">&#39;&#39;&#39;</span></span></code></pre></div>
<p>Und als <em>Hinweis</em>: Probieren Sie auch mal das Definieren und Laden des Datensatzes in einem RSkript (anstatt RMarkdown). Dort sollte dann auch die Tabulatortasten-Funktion möglich sein (unabhängig vom Speicherort des Skripts). Anschliessend können Sie den im Skript geschriebenen Kode in Ihr Markdown kopieren.</p>
<p> </p>
<ol start="2" style="list-style-type: decimal">
<li>Öffnen Sie nun die Datei “ESS1-8e01.csv” in einem Tabellenkalkulations- oder einem Textbearbeitungsprogramm (z.B. Microsoft Excel, dem Windows-Editor oder TextEdit auf Mac).</li>
</ol>
<ul>
<li>Vergleichen Sie die beiden Varianten (Ihr Dataframe in RStudio und die im Textbearbeitungsprogramm geöffnete Datei), um das Dateiformat “CSV” besser zu verstehen.</li>
<li>Ersetzen Sie anschliessend im Tabellenkalkulations- oder Textbearbeitungsprogramm die Kommas in der “ESS1-8e01.csv” Datei mit Strichpunkten und speichern Sie diese neue Version ab. Gehen Sie zurück zu R Studio und versuchen Sie, die neue Version des Datensatzes zu laden. Welchen Paramter müssen Sie anpassen, damit das funktioniert?</li>
<li>Was denken Sie könnten Vorteile des CSV-Formats sein? Welche möglichen Nachteile im Vergleich zu anderen Dateiformaten (Excel, SPSS …) sind denkbar?</li>
</ul>
<p>Das CSV-Dateiformat bietet eine sehr grundlegende Art und Weise um Daten oder eben Datensätze zu speichern. Indem die Kommas mit Strichpunkten ersetzt werden ändert sich das Zeichen, mit dem die Spalten bzw. Variablen getrennt werden. Die Fälle werden im Format jeweils über Zeilenumbrüche getrennt werden.</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="wochenplan-07.html#cb282-1" aria-hidden="true" tabindex="-1"></a>?read.csv</span></code></pre></div>
<p>Die <code>read.csv</code>-Funktion ermöglicht über das Argument <code>sep =</code> zu bestimmen, über welches Zeichen die Spalten eingelesen werden sollen. Wir definieren also über das Argument eine bestimmte Spezifizierung (es sind nicht die Standardwerte, die “,”) mit dem einem bestimmten Paramater (es sind neu “;”).</p>
<p>Das CSV-Dateiformat hat vor allem zwei Vorteile: Auf der einen Seite – und wie in der Teilaufgabe oben deutlich wurde – können über beliebige Texteditoren direkt in diese Daten eingegriffen werden, da im Format lediglich Rohdaten in Textform abgespeichert sind. Bei anderen Dateiformaten für Datensätze wie etwa .sav (von der Statistiksoftware SPSS) ist dies nicht so einfach möglich. Damit ist das CSV-Format ein besonders transparenter Standard, mit dem fast alle Programme und Betriebssysteme umgehen können. Auf der anderen Seite ist das CSV-Dateiformat nicht nur transparent, sondern beansprucht auch nur sehr wenig Speicherplatz. Grosse Datensätze können so schnell von RStudio gelesen und bereitgestellt werden. Die grosse Datensätze werden dadurch nicht komplexer, sondern womöglich lediglich unübersichtlich.</p>
<p>Dem gegenüber steht der Nachteil von CSV, dass das Dateiformat keine Möglichkeiten bietet, Informationen auf komplexere Art und Weise abzuspeichern (z.Bsp. Levels für kategoriale Variablenausprägungen oder das Speichern von mehr als zwei Dimensionen). CSV bleibt so ein Format für “Rohdaten.” Weiter besteht die Möglichkeit, dass Sonderzeichen in den Daten selbst zu Problemen führen (also etwa ein “,” als Teil einer Ausprägung, dass dann fälschlicherweise als Spaltenumbruch eingelesen würde).</p>
<p> </p>
<ol start="3" style="list-style-type: decimal">
<li>Versuchen Sie mit Funktionen, die Sie bisher kennengelernt haben, den geladenen Datensatz kurz zu beschreiben.</li>
</ol>
<p>Wir haben uns hier ein Objekt der Klasse…</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="wochenplan-07.html#cb283-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(daten_ess)</span></code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>geladen, dass Daten als…</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="wochenplan-07.html#cb285-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(daten_ess)</span></code></pre></div>
<pre><code>## [1] &quot;list&quot;</code></pre>
<p>abspeichert.</p>
<p>Unser Datensatz umfasst..</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="wochenplan-07.html#cb287-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(daten_ess)[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 1525</code></pre>
<p>Fälle mit jeweils…</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="wochenplan-07.html#cb289-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(daten_ess)[<span class="dv">2</span>]</span></code></pre></div>
<pre><code>## [1] 21</code></pre>
<p>Variablen.</p>
<p>Die zweite und die zweitletzte Variablen heisst etwa:</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="wochenplan-07.html#cb291-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(daten_ess)[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">21</span>)]</span></code></pre></div>
<pre><code>## [1] &quot;x&quot;        &quot;hinctnta&quot;</code></pre>
<p>Die ersten fünf Variablen – alphabetisch geordnet – heissen:</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="wochenplan-07.html#cb293-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">names</span>(daten_ess))[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span></code></pre></div>
<pre><code>## [1] &quot;agea&quot;    &quot;chldhm&quot;  &quot;cntry&quot;   &quot;edctn&quot;   &quot;edulvla&quot;</code></pre>
<p>Aktuell umfasst der Datensatz nur metrische Daten und eine eine Character-Variable als Konstante.<a href="#fn10" class="footnote-ref" id="fnref10"><sup>10</sup></a> Auch eine Variable wie “gndr” ist daher eine Zahl in dem Datensatz und wird aktuell von RStudio als ein numerischer Vektor behandelt. Die Funktion <code>str()</code> liefert hierfür eine Übersicht, in dem sie die interne Struktur eines R-Objekts aufzeigt. Für unseren Datensatz bedeutet dies: die Variablen (auf welche wir mit <code>$</code> zugreifen können), deren Dateiformat sowie deren ersten paar Ausprägungen.</p>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="wochenplan-07.html#cb295-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(daten_ess)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    1525 obs. of  21 variables:
##  $ x       : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ cntry   : chr  &quot;CH&quot; &quot;CH&quot; &quot;CH&quot; &quot;CH&quot; ...
##  $ essround: int  8 8 8 8 8 8 8 8 8 8 ...
##  $ idno    : int  1 3 5 6 9 14 21 22 24 27 ...
##  $ pspwght : num  0.9 1.1 1.02 1.09 1.03 ...
##  $ pweight : num  0.465 0.465 0.465 0.465 0.465 ...
##  $ polintr : int  2 2 2 3 2 2 2 3 2 1 ...
##  $ happy   : int  8 6 8 8 8 5 9 3 8 10 ...
##  $ gndr    : int  1 2 1 2 1 1 1 2 2 2 ...
##  $ yrbrn   : int  1960 1953 1987 1949 1963 1948 1961 1955 1980 1941 ...
##  $ agea    : int  56 63 29 67 53 68 55 61 36 75 ...
##  $ chldhm  : int  2 2 2 2 2 2 2 2 2 2 ...
##  $ edulvla : int  3 3 5 2 3 3 3 2 5 4 ...
##  $ eisced  : int  3 3 7 2 3 3 3 2 6 5 ...
##  $ eduyrs  : int  9 12 18 9 10 9 9 8 13 16 ...
##  $ pdwrk   : int  1 1 1 0 0 0 1 0 1 0 ...
##  $ edctn   : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ wkhtot  : int  60 20 50 37 44 46 45 44 24 55 ...
##  $ isco08  : int  1200 5419 2210 5223 7112 4220 8300 8100 5223 1120 ...
##  $ uemp3m  : int  1 1 2 2 1 1 2 2 2 1 ...
##  $ hinctnta: int  10 1 10 1 77 2 5 77 4 5 ...</code></pre>
<p>Über die <code>summary()</code>-Funktion wird auch nochmals deutlich, dass hier tatsächlich Rohdaten eingelesen wurden: Auch fehlende Werte gelten aktuell noch als gültige Zahlen (…jemand wäre also im Jahr 7777 geboren).</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="wochenplan-07.html#cb297-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(daten_ess<span class="sc">$</span>yrbrn)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1922    1954    1968    1991    1984    7777</code></pre>
<p>Weiter sehen wir, dass sogenannte <em>Dummy</em>-Variablen oft 1-2 anstatt 0-1 kodiert sind.</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="wochenplan-07.html#cb299-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(daten_ess<span class="sc">$</span>chldhm)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   1.000   2.000   1.656   2.000   2.000</code></pre>
<p>…oder wir sehen, dass Geschlecht ziemlich gleichmässig verteilt zu sein scheint:</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="wochenplan-07.html#cb301-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(daten_ess<span class="sc">$</span>gndr)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   1.000   1.000   1.483   2.000   2.000</code></pre>
<p> </p>
<ol start="4" style="list-style-type: decimal">
<li>In den Variablen zum Alter und den Bildungsabschlüssen der befragten Personen haben sich einige Fehler eingeschlichen. Was sind die Fehler? Und welche Fälle betrifft das (Fallnummer)?</li>
</ol>
<p>Wir können drei Stufen von Plausibilitätstests unterscheiden:<br />
Bei der <em>ersten Stufe</em> betrachten wir lediglich die Zahlen selber, wobei uns vor allem Häufigkeitsverteilungen und Extremwerten interessiert. Wir beginnen mit der Variable zum Alter:</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="wochenplan-07.html#cb303-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(daten_ess<span class="sc">$</span>agea)</span></code></pre></div>
<pre><code>## [1] 14</code></pre>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="wochenplan-07.html#cb305-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(daten_ess<span class="sc">$</span>agea)</span></code></pre></div>
<pre><code>## [1] 999</code></pre>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="wochenplan-07.html#cb307-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(daten_ess<span class="sc">$</span>agea)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   14.00   32.00   48.00   51.75   63.00  999.00</code></pre>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="wochenplan-07.html#cb309-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(daten_ess<span class="sc">$</span>agea<span class="sc">==</span><span class="dv">999</span>)</span></code></pre></div>
<pre><code>## [1] 121 196 320 717 791 800</code></pre>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="wochenplan-07.html#cb311-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(daten_ess<span class="sc">$</span>agea<span class="sc">&gt;</span><span class="dv">120</span>)</span></code></pre></div>
<pre><code>## [1] 121 132 196 320 717 791 800</code></pre>
<p>Hier scheint nun ein erster Fehler sichtbar zu sein, nämlich beim <strong>Fall 132</strong>. Diese Person soll angeblich 320 Jahre alt sein:</p>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="wochenplan-07.html#cb313-1" aria-hidden="true" tabindex="-1"></a>daten_ess<span class="sc">$</span>agea[<span class="dv">132</span>]</span></code></pre></div>
<pre><code>## [1] 320</code></pre>
<p>Die Werte zu den Bildungsabschlüssen sind kategoriale Daten. Deshalb lohnt es sich hier mit Tabellen zu arbeiten, um Häufigkeitsverteilungen und Extremwerte zu betrachten:</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="wochenplan-07.html#cb315-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(daten_ess<span class="sc">$</span>edulvla)</span></code></pre></div>
<pre><code>## 
##   1   2   3   4   5  55  77  88 
##  51 265 665  45 491   3   1   4</code></pre>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="wochenplan-07.html#cb317-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(daten_ess<span class="sc">$</span>eisced)</span></code></pre></div>
<pre><code>## 
##   0   1   2   3   4   5   6   7  55  77  88 
##   1  50 265 543 122 226 114 197   3   1   3</code></pre>
<p>Hier scheint noch nicht wirklich ein Fehler sichtbar zu sein.</p>
<p>Auf der <em>zweiten Stufe</em> überprüfen wir nun, ob die Daten auch wirklich Sinn machen, das heisst im Rahmen der Codierungen gemäss Fragebogen. So wird schnell deutlich, dass wir natürlich fehlende Werte auf eine bestimmte Art und Weise in unserem Datensatz vorfinden. Beim Alter ist dies 999 (“Not available”), während es bei den Bildungsabschlüssen die Ausprägungen 55 (“Other”), 77 (“Refusal”), 88 (“Don’t know”) und 99 (“No answer”) sind. Diese Ausprägungen können wir dann als fehlende Werte, sogenannte <code>NAs</code> definieren:</p>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="wochenplan-07.html#cb319-1" aria-hidden="true" tabindex="-1"></a>daten_ess<span class="sc">$</span>agea[daten_ess<span class="sc">$</span>agea<span class="sc">==</span><span class="dv">999</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb319-2"><a href="wochenplan-07.html#cb319-2" aria-hidden="true" tabindex="-1"></a>daten_ess<span class="sc">$</span>edulvla[daten_ess<span class="sc">$</span>edulvla<span class="sc">&gt;</span><span class="dv">5</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb319-3"><a href="wochenplan-07.html#cb319-3" aria-hidden="true" tabindex="-1"></a>daten_ess<span class="sc">$</span>eisced[daten_ess<span class="sc">$</span>eisced<span class="sc">&gt;</span><span class="dv">7</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code></pre></div>
<p>Ein Vergleich mit dem Codebuch zeigt dabei aber auch, dass erst Personen ab dem 15. Lebensjahr befragt wurden. Folgender <strong>Fall 352</strong> macht also keinen Sinn:</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="wochenplan-07.html#cb320-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(daten_ess<span class="sc">$</span>agea<span class="sc">&lt;</span><span class="dv">15</span>)</span></code></pre></div>
<pre><code>## [1] 352</code></pre>
<p>Hingegen ist die bei der Variable eisced auftauchende Ausprägung ‘0’ ist durchaus zulässig und entspricht “Not possible to harmonise into ES-ISCED.”</p>
<p>Auf der <em>dritten Stufe</em> vergleichen wir dann mittels Kreuztabellierungen und logischen Überlegungen jeweils (mindestens) zwei Variablen miteinander, um so nochmals Fehler zu entdecken. Dieses könnten wir mittels eines Plots machen, wie dies etwa Vanessa Leutner vorgeschlagen hat:</p>
<div class="sourceCode" id="cb322"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb322-1"><a href="wochenplan-07.html#cb322-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(daten_ess<span class="sc">$</span>agea, daten_ess<span class="sc">$</span>yrbrn, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">100</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">1900</span>,<span class="dv">2017</span>))</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-126-1.png" width="672" />
Dann können wir eine zusätzliche Variable berechnen, die als Fehlerindikator für die Angaben zum Alter dient. Diese zusätzliche Variable nutzen wir dann als logische Bedingung, um fehlerhafte Fälle zu entdecken:</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="wochenplan-07.html#cb323-1" aria-hidden="true" tabindex="-1"></a>daten_ess<span class="sc">$</span>agea_l <span class="ot">&lt;-</span> daten_ess<span class="sc">$</span>agea <span class="sc">+</span> daten_ess<span class="sc">$</span>yrbrn</span>
<span id="cb323-2"><a href="wochenplan-07.html#cb323-2" aria-hidden="true" tabindex="-1"></a>daten_ess<span class="sc">$</span>agea_l[daten_ess<span class="sc">$</span>agea_l<span class="sc">!=</span><span class="dv">2016</span>]</span></code></pre></div>
<pre><code>##  [1] 2017 2017 2017 2017 2017 2017 2017 2017   NA 2017 2304 2017   NA 2017 2017
## [16] 2017   NA 2017 2017 2017 1990 2017 2017 2017 2017 2017 2017 2017 2017 2017
## [31] 2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 2017   NA
## [46] 2017 2017 2017   NA   NA 2017 2017 2017 2017 2017 2017 2017 2017 2017 2017
## [61] 2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 2017 2017
## [76] 2017 2017 2017 2017 1962 2017 2017 2017 2017 2017 2017 2017 2017 2017</code></pre>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="wochenplan-07.html#cb325-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(daten_ess<span class="sc">$</span>agea_l<span class="sc">!=</span><span class="dv">2016</span> <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>agea_l<span class="sc">!=</span><span class="dv">2017</span>)</span></code></pre></div>
<pre><code>## [1]  132  352 1414</code></pre>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="wochenplan-07.html#cb327-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Identifikation der Fälle</span></span>
<span id="cb327-2"><a href="wochenplan-07.html#cb327-2" aria-hidden="true" tabindex="-1"></a>daten_ess[daten_ess<span class="sc">$</span>agea_l<span class="sc">!=</span><span class="dv">2016</span> </span>
<span id="cb327-3"><a href="wochenplan-07.html#cb327-3" aria-hidden="true" tabindex="-1"></a>          <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>agea_l<span class="sc">!=</span><span class="dv">2017</span></span>
<span id="cb327-4"><a href="wochenplan-07.html#cb327-4" aria-hidden="true" tabindex="-1"></a>          <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(daten_ess<span class="sc">$</span>agea_l),<span class="fu">c</span>(<span class="st">&quot;agea&quot;</span>, <span class="st">&quot;yrbrn&quot;</span>)]</span></code></pre></div>
<pre><code>##      agea yrbrn
## 132   320  1984
## 352    14  1976
## 1414   23  1939</code></pre>
<p>Neben den bereits bekannten beiden Fällen (132 &amp; 352) wir so auch noch der dritte falsche Fehler im Datensatz bei der Altersvariable deutlich, nämlich <strong>Fall 1414</strong>.<br />
Bei den Angaben zum Bildungsniveau wieder können wir stärker Kreuztabellen nutzen, um zwei Fehler zu entdecken:</p>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="wochenplan-07.html#cb329-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(daten_ess<span class="sc">$</span>edulvla, daten_ess<span class="sc">$</span>eisced)</span></code></pre></div>
<pre><code>##    
##       0   1   2   3   4   5   6   7
##   1   0  50   0   0   0   1   0   0
##   2   0   0 265   0   0   0   0   0
##   3   0   0   0 543 122   0   0   0
##   4   0   0   0   0   0  45   0   0
##   5   0   0   0   0   0 180 114 197</code></pre>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="wochenplan-07.html#cb331-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(daten_ess<span class="sc">$</span>eduyrs, daten_ess<span class="sc">$</span>edulvla)</span></code></pre></div>
<pre><code>##     
##        1   2   3   4   5
##   0    2   1   0   0   0
##   1    1   0   1   0   0
##   2    1   2   0   0   0
##   3    1   0   0   0   0
##   4    4   1   0   0   0
##   5    2   4   0   0   0
##   6   12   5   3   0   1
##   7    5   1   3   0   0
##   8    5  44  52   2   9
##   9   13 125 302  24  91
##   10   1  34  71   6  20
##   11   1  22  30   1  12
##   12   3  19  82   1  62
##   13   0   4  43   2  38
##   14   0   0  39   2  31
##   15   0   3  12   3  32
##   16   0   0  13   3  37
##   17   0   0   5   1  48
##   18   0   0   3   0  52
##   19   0   0   4   0  29
##   20   0   0   0   0  13
##   21   0   0   0   0   6
##   22   0   0   0   0   5
##   23   0   0   1   0   3
##   25   0   0   0   0   1
##   26   0   0   0   0   1
##   77   0   0   0   0   0
##   88   0   0   1   0   0</code></pre>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="wochenplan-07.html#cb333-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(daten_ess<span class="sc">$</span>eduyrs, daten_ess<span class="sc">$</span>eisced)</span></code></pre></div>
<pre><code>##     
##        0   1   2   3   4   5   6   7
##   0    0   2   1   0   0   0   0   0
##   1    0   1   0   1   0   0   0   0
##   2    0   1   2   0   0   0   0   0
##   3    0   1   0   0   0   0   0   0
##   4    0   4   1   0   0   0   0   0
##   5    0   2   4   0   0   0   0   0
##   6    0  12   5   3   0   1   0   0
##   7    0   5   1   3   0   0   0   0
##   8    0   5  44  49   3   9   0   2
##   9    0  13 125 287  15  90  12  13
##   10   0   1  34  67   4  22   3   1
##   11   0   1  22  20  10  10   2   1
##   12   1   2  19  55  27  23  15  26
##   13   0   0   4  23  20  21  10   9
##   14   0   0   0  18  21  14   8  11
##   15   0   0   3   5   7  11  15   9
##   16   0   0   0   6   7  11  15  14
##   17   0   0   0   1   4   6  15  28
##   18   0   0   0   1   2   6  13  33
##   19   0   0   0   2   2   1   4  24
##   20   0   0   0   0   0   1   1  11
##   21   0   0   0   0   0   0   0   6
##   22   0   0   0   0   0   0   1   4
##   23   0   0   0   1   0   0   0   3
##   25   0   0   0   0   0   0   0   1
##   26   0   0   0   0   0   0   0   1
##   77   0   0   0   0   0   0   0   0
##   88   0   0   0   1   0   0   0   0</code></pre>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="wochenplan-07.html#cb335-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Identifikation der Fälle</span></span>
<span id="cb335-2"><a href="wochenplan-07.html#cb335-2" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(daten_ess<span class="sc">$</span>edulvla<span class="sc">==</span><span class="dv">1</span> <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>eisced<span class="sc">==</span><span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 443</code></pre>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="wochenplan-07.html#cb337-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(daten_ess<span class="sc">$</span>edulvla<span class="sc">==</span><span class="dv">3</span> <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>eisced<span class="sc">==</span><span class="dv">3</span> <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>eduyrs<span class="sc">&lt;</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 1482</code></pre>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="wochenplan-07.html#cb339-1" aria-hidden="true" tabindex="-1"></a>daten_ess[<span class="fu">c</span>(<span class="fu">which</span>(daten_ess<span class="sc">$</span>edulvla<span class="sc">==</span><span class="dv">1</span> <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>eisced<span class="sc">==</span><span class="dv">5</span>),</span>
<span id="cb339-2"><a href="wochenplan-07.html#cb339-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">which</span>(daten_ess<span class="sc">$</span>edulvla<span class="sc">==</span><span class="dv">3</span> <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>eisced<span class="sc">==</span><span class="dv">3</span> <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>eduyrs<span class="sc">&lt;</span><span class="dv">6</span>)),</span>
<span id="cb339-3"><a href="wochenplan-07.html#cb339-3" aria-hidden="true" tabindex="-1"></a>          <span class="fu">c</span>(<span class="st">&quot;edulvla&quot;</span>, <span class="st">&quot;eisced&quot;</span>)]</span></code></pre></div>
<pre><code>##      edulvla eisced
## 443        1      5
## 1482       3      3</code></pre>
<p>Wir finden so zwei Fälle entdeckt, bei denen Fehler in den Bildungsabschlüssen drin stecken, nämlich <strong>Fall 443</strong> und <strong>Fall 1482</strong>.</p>
<p>Josias Bruderer hat für ein solches Fehlersuchen mittels logischer Bedingungen auch die Alters- und Bildungsvariablen kombiniert:</p>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="wochenplan-07.html#cb341-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Menschen die vor 3 Jahren in die Schule kamen</span></span>
<span id="cb341-2"><a href="wochenplan-07.html#cb341-2" aria-hidden="true" tabindex="-1"></a>errors_a <span class="ot">&lt;-</span> <span class="fu">which</span>(daten_ess<span class="sc">$</span>agea <span class="sc">&lt;</span> (daten_ess<span class="sc">$</span>eduyrs) <span class="sc">+</span> <span class="dv">3</span> </span>
<span id="cb341-3"><a href="wochenplan-07.html#cb341-3" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>agea <span class="sc">&lt;</span> <span class="dv">999</span> <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>eduyrs <span class="sc">&lt;</span> <span class="dv">77</span>)</span>
<span id="cb341-4"><a href="wochenplan-07.html#cb341-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb341-5"><a href="wochenplan-07.html#cb341-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Menschen mit Fehler im Bildungsabschluss gem. Definition ES-ISCED</span></span>
<span id="cb341-6"><a href="wochenplan-07.html#cb341-6" aria-hidden="true" tabindex="-1"></a>errors_b <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb341-7"><a href="wochenplan-07.html#cb341-7" aria-hidden="true" tabindex="-1"></a>errors_b <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_b, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">1</span> </span>
<span id="cb341-8"><a href="wochenplan-07.html#cb341-8" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">&gt;</span> <span class="dv">1</span> </span>
<span id="cb341-9"><a href="wochenplan-07.html#cb341-9" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">&lt;</span> <span class="dv">55</span>))</span>
<span id="cb341-10"><a href="wochenplan-07.html#cb341-10" aria-hidden="true" tabindex="-1"></a>errors_b <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_b, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">2</span> </span>
<span id="cb341-11"><a href="wochenplan-07.html#cb341-11" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">!=</span> <span class="dv">2</span> </span>
<span id="cb341-12"><a href="wochenplan-07.html#cb341-12" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">&lt;</span> <span class="dv">55</span>))</span>
<span id="cb341-13"><a href="wochenplan-07.html#cb341-13" aria-hidden="true" tabindex="-1"></a>errors_b <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_b, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">3</span> </span>
<span id="cb341-14"><a href="wochenplan-07.html#cb341-14" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">!=</span> <span class="dv">3</span> </span>
<span id="cb341-15"><a href="wochenplan-07.html#cb341-15" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">&lt;</span> <span class="dv">55</span>))</span>
<span id="cb341-16"><a href="wochenplan-07.html#cb341-16" aria-hidden="true" tabindex="-1"></a>errors_b <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_b, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">4</span> </span>
<span id="cb341-17"><a href="wochenplan-07.html#cb341-17" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">!=</span> <span class="dv">3</span> </span>
<span id="cb341-18"><a href="wochenplan-07.html#cb341-18" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">&lt;</span> <span class="dv">55</span>))</span>
<span id="cb341-19"><a href="wochenplan-07.html#cb341-19" aria-hidden="true" tabindex="-1"></a>errors_b <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_b, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">5</span> </span>
<span id="cb341-20"><a href="wochenplan-07.html#cb341-20" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">!=</span> <span class="dv">4</span> </span>
<span id="cb341-21"><a href="wochenplan-07.html#cb341-21" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">!=</span> <span class="dv">5</span> </span>
<span id="cb341-22"><a href="wochenplan-07.html#cb341-22" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">&lt;</span> <span class="dv">55</span>))</span>
<span id="cb341-23"><a href="wochenplan-07.html#cb341-23" aria-hidden="true" tabindex="-1"></a>errors_b <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_b, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">6</span> </span>
<span id="cb341-24"><a href="wochenplan-07.html#cb341-24" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">!=</span> <span class="dv">5</span> </span>
<span id="cb341-25"><a href="wochenplan-07.html#cb341-25" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">&lt;</span> <span class="dv">55</span>))</span>
<span id="cb341-26"><a href="wochenplan-07.html#cb341-26" aria-hidden="true" tabindex="-1"></a>errors_b <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_b, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">7</span> </span>
<span id="cb341-27"><a href="wochenplan-07.html#cb341-27" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">!=</span> <span class="dv">5</span> </span>
<span id="cb341-28"><a href="wochenplan-07.html#cb341-28" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>edulvla <span class="sc">&lt;</span> <span class="dv">55</span>))</span>
<span id="cb341-29"><a href="wochenplan-07.html#cb341-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb341-30"><a href="wochenplan-07.html#cb341-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb341-31"><a href="wochenplan-07.html#cb341-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Menschen mit &quot;unlogischem&quot; Alter für Bildungsabschluss gem. ES-ISCED</span></span>
<span id="cb341-32"><a href="wochenplan-07.html#cb341-32" aria-hidden="true" tabindex="-1"></a>errors_c <span class="ot">&lt;-</span> <span class="fu">c</span>()</span>
<span id="cb341-33"><a href="wochenplan-07.html#cb341-33" aria-hidden="true" tabindex="-1"></a>errors_c <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_c, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">1</span> </span>
<span id="cb341-34"><a href="wochenplan-07.html#cb341-34" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>agea <span class="sc">&lt;</span> <span class="dv">11</span>))</span>
<span id="cb341-35"><a href="wochenplan-07.html#cb341-35" aria-hidden="true" tabindex="-1"></a>errors_c <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_c, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">2</span> </span>
<span id="cb341-36"><a href="wochenplan-07.html#cb341-36" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>agea <span class="sc">&lt;</span> <span class="dv">14</span>))</span>
<span id="cb341-37"><a href="wochenplan-07.html#cb341-37" aria-hidden="true" tabindex="-1"></a>errors_c <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_c, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">3</span> </span>
<span id="cb341-38"><a href="wochenplan-07.html#cb341-38" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>agea <span class="sc">&lt;</span> <span class="dv">16</span>))</span>
<span id="cb341-39"><a href="wochenplan-07.html#cb341-39" aria-hidden="true" tabindex="-1"></a>errors_c <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_c, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">4</span> </span>
<span id="cb341-40"><a href="wochenplan-07.html#cb341-40" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>agea <span class="sc">&lt;</span> <span class="dv">16</span>))</span>
<span id="cb341-41"><a href="wochenplan-07.html#cb341-41" aria-hidden="true" tabindex="-1"></a>errors_c <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_c, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">5</span> </span>
<span id="cb341-42"><a href="wochenplan-07.html#cb341-42" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>agea <span class="sc">&lt;</span> <span class="dv">18</span>))</span>
<span id="cb341-43"><a href="wochenplan-07.html#cb341-43" aria-hidden="true" tabindex="-1"></a>errors_c <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_c, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">6</span> </span>
<span id="cb341-44"><a href="wochenplan-07.html#cb341-44" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>agea <span class="sc">&lt;</span> <span class="dv">20</span>))</span>
<span id="cb341-45"><a href="wochenplan-07.html#cb341-45" aria-hidden="true" tabindex="-1"></a>errors_c <span class="ot">&lt;-</span> <span class="fu">c</span>(errors_c, <span class="fu">which</span>(daten_ess<span class="sc">$</span>eisced <span class="sc">==</span> <span class="dv">7</span> </span>
<span id="cb341-46"><a href="wochenplan-07.html#cb341-46" aria-hidden="true" tabindex="-1"></a>                              <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>agea <span class="sc">&lt;</span> <span class="dv">20</span>))</span>
<span id="cb341-47"><a href="wochenplan-07.html#cb341-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb341-48"><a href="wochenplan-07.html#cb341-48" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">unique</span>(<span class="fu">c</span>(errors_a, errors_b, errors_c)))</span></code></pre></div>
<pre><code>## [1] 352 443</code></pre>
<p>Im <em>Umgang mit diesen fehlenden Werten</em> haben wir drei Möglichkeiten:<br />
Wir können die benötigen Angaben von anderen Werten ableiten (1), zum Beispiel das Alter vom Geburtsjahr.</p>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="wochenplan-07.html#cb343-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(daten_ess<span class="sc">$</span>agea<span class="sc">&gt;</span><span class="dv">120</span>)</span></code></pre></div>
<pre><code>## [1] 132</code></pre>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="wochenplan-07.html#cb345-1" aria-hidden="true" tabindex="-1"></a>daten_ess<span class="sc">$</span>agea[<span class="dv">132</span>]</span></code></pre></div>
<pre><code>## [1] 320</code></pre>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="wochenplan-07.html#cb347-1" aria-hidden="true" tabindex="-1"></a>daten_ess<span class="sc">$</span>agea[<span class="dv">132</span>] <span class="ot">&lt;-</span> <span class="dv">2016</span> <span class="sc">-</span> daten_ess<span class="sc">$</span>yrbrn[<span class="dv">132</span>]</span>
<span id="cb347-2"><a href="wochenplan-07.html#cb347-2" aria-hidden="true" tabindex="-1"></a>daten_ess<span class="sc">$</span>agea[<span class="dv">132</span>]</span></code></pre></div>
<pre><code>## [1] 32</code></pre>
<p>Weiter können wir uns einen Wert berechnen bzw. diesen schätzen (2):</p>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="wochenplan-07.html#cb349-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(daten_ess<span class="sc">$</span>edulvla<span class="sc">==</span><span class="dv">3</span> <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>eisced<span class="sc">==</span><span class="dv">3</span> <span class="sc">&amp;</span> daten_ess<span class="sc">$</span>eduyrs<span class="sc">&lt;</span><span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 1482</code></pre>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="wochenplan-07.html#cb351-1" aria-hidden="true" tabindex="-1"></a>daten_ess<span class="sc">$</span>eduyrs[<span class="dv">1482</span>] <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">mean</span>(daten_ess<span class="sc">$</span>eduyrs[daten_ess<span class="sc">$</span>edulvla<span class="sc">==</span><span class="dv">3</span>],</span>
<span id="cb351-2"><a href="wochenplan-07.html#cb351-2" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">na.rm =</span> T))</span>
<span id="cb351-3"><a href="wochenplan-07.html#cb351-3" aria-hidden="true" tabindex="-1"></a>daten_ess<span class="sc">$</span>eduyrs[<span class="dv">1482</span>]</span></code></pre></div>
<pre><code>## [1] 11</code></pre>
<p>Die letzte Option ist dann noch die falschen Angaben als fehlende Werte zu definieren (3):</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="wochenplan-07.html#cb353-1" aria-hidden="true" tabindex="-1"></a>daten_ess<span class="sc">$</span>edulvla[<span class="dv">443</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span></code></pre></div>
<p> </p>
<ol start="5" style="list-style-type: decimal">
<li><em>Bonusaufgabe</em>: In den folgenden Wochen möchten wir nicht mit dem ganzen Datensatz arbeiten, sondern lediglich mit einer zufälligen Auswahl von 200 Fällen. Versuchen Sie, einen solchen Teildatensatz randomisiert zu erstellen und speichern Sie ihn mittels der Funktion ‘write.csv()’ unter dem Namen “TD_ESS1-8e01.csv” ab.</li>
</ol>
<p>Um den zufälligen Datensatz mit 200 Fällen zu erstellen bieten sich mindestens zwei Möglichkeiten an:<br />
Die erste Möglichkeit nutzt die <code>sample()</code>-Funktion und wählt zufällig 200 Zahlen einer Variable aus, die von 1 bis 1525 durchläuft. Eine solche Variable ist “x” im Datensatz – oder auch einfach die Zeilenzahl. Die zufällig ausgewählten Zahlen dieser Variable können als Angabe für die Zeilen in die eckige Klammerfunktion eingesetzt werden.</p>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="wochenplan-07.html#cb354-1" aria-hidden="true" tabindex="-1"></a>daten_ess_HS20 <span class="ot">&lt;-</span> daten_ess[<span class="fu">sample</span>(<span class="fu">row.names</span>(daten_ess),<span class="dv">200</span>),]</span>
<span id="cb354-2"><a href="wochenplan-07.html#cb354-2" aria-hidden="true" tabindex="-1"></a><span class="co">#oder auch:</span></span>
<span id="cb354-3"><a href="wochenplan-07.html#cb354-3" aria-hidden="true" tabindex="-1"></a>daten_ess_HS20 <span class="ot">&lt;-</span> daten_ess[<span class="fu">sample</span>(daten_ess<span class="sc">$</span>x,<span class="dv">200</span>),]</span></code></pre></div>
<p>Die zweite Möglichkeit berechnet eine Zufallsvariable und sortiert den Datensatz dann nach der Grösse dieser Zufallsvariable. Anschliessend können dann die – jetzt völlig zufällig – ersten 200 Fälle ausgewählt werden.</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="wochenplan-07.html#cb355-1" aria-hidden="true" tabindex="-1"></a>daten_ess<span class="sc">$</span>zv <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">1525</span>)</span>
<span id="cb355-2"><a href="wochenplan-07.html#cb355-2" aria-hidden="true" tabindex="-1"></a>daten_ess <span class="ot">&lt;-</span> daten_ess[<span class="fu">order</span>(daten_ess<span class="sc">$</span>zv),]</span>
<span id="cb355-3"><a href="wochenplan-07.html#cb355-3" aria-hidden="true" tabindex="-1"></a>daten_ess_HS20 <span class="ot">&lt;-</span> daten_ess[<span class="dv">1</span><span class="sc">:</span><span class="dv">200</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">22</span>]</span></code></pre></div>
<p>Neben diesen beiden Möglichkeiten haben weitere Seminarteilnehmer*innen auch Ideen geliefert.<br />
Josias Bruder und Fabio Keller haben die erste Möglichkeit etwas ergänzt:</p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="wochenplan-07.html#cb356-1" aria-hidden="true" tabindex="-1"></a>daten_ess_HS20 <span class="ot">&lt;-</span> daten_ess[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(daten_ess),<span class="dv">200</span>),]</span></code></pre></div>
<p>Ebenso wie Felix Sigrist:</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="wochenplan-07.html#cb357-1" aria-hidden="true" tabindex="-1"></a>daten_ess_HS20 <span class="ot">&lt;-</span> daten_ess[<span class="fu">sample</span>(<span class="fu">nrow</span>(daten_ess),<span class="dv">200</span>),]</span></code></pre></div>
<p>Delia Bazzigher und Julien Lattmann schlagen weiter die Funktion <code>sample_n</code> aus dem “dpylr” Paket vor (dieses ist Teil der Kernpakete des “tidyverse”):</p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb358-1"><a href="wochenplan-07.html#cb358-1" aria-hidden="true" tabindex="-1"></a><span class="co">#installed.packages(&quot;dplyr&quot;)</span></span>
<span id="cb358-2"><a href="wochenplan-07.html#cb358-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb358-3"><a href="wochenplan-07.html#cb358-3" aria-hidden="true" tabindex="-1"></a>daten_ess_HS20 <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(daten_ess, <span class="dv">200</span>)</span></code></pre></div>
<p>Der zufällige erstellte Datensatz kann anschliessend wiederum als CSV-Datei abgespeichert werden (die Datei wird dann im Arbeitsordner abgelegt):</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="wochenplan-07.html#cb359-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(daten_ess_HS20, <span class="at">file =</span> <span class="st">&quot;Daten/ESS1-8e01_HS21.csv&quot;</span>)</span></code></pre></div>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="9">
<li id="fn9"><p>Die RStudio-Projekten erlauben es Ihnen, Ihre Arbeit in mehrere Kontexte aufteilen, die jeweils über ein eigenes Arbeitsverzeichnis, einen eigenen Arbeitsbereich, einen eigenen Verlauf und eigene Quelldokumente verfügen. Sie sind eben nochmals abgeschlossene Projekte innerhalb von RStudio und können über die Menüsteuerung “File” -&gt; “New Project…” gestartet werden.<a href="wochenplan-07.html#fnref9" class="footnote-back">↩︎</a></p></li>
<li id="fn10"><p>Wiederum spezifiziert bei numerische Daten dass <code>int</code> ganze Zahlen und <code>num</code> komplexe Zahlen sind (mit Kommastellen, negative Werte, usw.)<a href="wochenplan-07.html#fnref10" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="wochenplan-06.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="wochenplan-08.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/07_WP07_Datenaufbereitung.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
